#!/bin/sh
. `dirname $0`/buzexe_tool
if [ ! $3 ]; then
  echo "作者: CN_obi"
  echo "版本: 2.1.2"
  echo "版本号: 11"
  echo
  echo "使用方法: `basename $0` [缓存路径] [是否打包同级目录(布尔值)] [脚本路径] [输出路径(可选)]"
  echo "缓存路径要求[可读][可写][可执行]"
  echo "推荐缓存目录: "
  echo "Linux: /usr/tmp"
  echo "Android: /sdcard/data/tmp"
  echo "Android(Root): /data/tmp"
  exit 0
else
  if [ -f $3 ]; then
    if [[ ${3} = ${3%.*} ]]; then
      filename="${3}_`basename $0`"
    else
      filename="${3%.*}_`basename $0`.${3##*.}"
    fi
    if [ ! $4 ]; then
      OUTPUT=$filename
    else
      OUTPUT=$4
    fi
    TAR_FILE=${OUTPUT}.tar.gz
    cd `dirname $3`
    if $2; then
      tar -czvf $TAR_FILE ./ > /dev/null
    else
      tar -czvf $TAR_FILE `basename $3` > /dev/null
    fi
    cd $OLDPWD
    echo "#!/bin/sh">$OUTPUT
    echo "TMP=${1}/\$\$">>$OUTPUT
    echo "SKIP=28">>$OUTPUT
    echo "SCRIPT=\"`basename $3`\"">>$OUTPUT
    tail -n +54 "$0">>$OUTPUT
    base64 -w 76 $TAR_FILE >>$OUTPUT
    rm -rf $TAR_FILE
    if check "$OUTPUT"; then
      echo "加密成功!"
      exit 0
    else
      echo "加密失败!" 1>&2
      exit 1
    fi
  else
    echo "文件不存在!" 1>&2
    exit 1
  fi
fi
PROG="${TMP}/`basename $0`"
mkdir -m=rwx -p $TMP
touch $PROG
tail -n +$SKIP "$0" | base64 -d > ${PROG}.tar.gz
cd $TMP
tar -xzvf `basename $0`.tar.gz > /dev/null
cd $OLDPWD
if [ $? -eq 0 ]; then
  sh=`sed -n '1p' ${TMP}/${SCRIPT}`
  if echo "$sh" | grep '\#\!/.*' > /dev/null; then
    sh=${sh#*\#\!}
  else
    sh=$SHELL
  fi
  $sh ${TMP}/${SCRIPT} $@
  res=$?
  rm -rf $TMP
  exit $res
else
  echo "解包失败!" 1>&2
  rm -rf $TMP
  exit 1
fi
